feat: allow for convert script to be based on arbitrary artifacts

diff --git a/builder/make_get_image_dependencies b/builder/make_get_image_dependencies
--- a/builder/make_get_image_dependencies
+++ b/builder/make_get_image_dependencies
@@ -3,7 +3,7 @@
 set -eufo pipefail
 
 exec 3>&1
-exec 1>&1
+exec 1>&2
 
 # get longest chain of extensions, but not extensions starting with a number to prevent parsing minor version as extension
 extension="$(grep -E -o '(\.[a-z][a-zA-Z0-9\-_]*)*$' <<< "$1")"
@@ -48,6 +48,21 @@ for feature in "${features[@]}"; do
 		script="features/$feature/convert$extension"
 		input="$artifact_base-$COMMIT.raw"
 	fi
+
+	shopt -s nullglob
+	set +f
+	advanced_convert_scripts=("features/$feature/convert${extension:-.raw}~"*)
+	set -f
+
+	for i in "${advanced_convert_scripts[@]}"; do
+		if [ "$is_feature_script" = 1 ]; then
+			printf "error: %s conflicts with %s\n" "$script" "$i"
+			exit 1
+		fi
+		is_feature_script=1
+		script="$i"
+		input="$artifact_base-$COMMIT.${i##*~}"
+	done
 done
 
 if [ -z "$script" ]; then
@@ -55,4 +70,5 @@ if [ -z "$script" ]; then
 	exit 1
 fi
 
+# printf 'DEBUG: [%s] %s -> %s %s\n' "$0" "$*" "$script" "$input" >&2
 printf '%s %s\n' "$script" "$input" >&3
